trigger:
- master
- rel/*

jobs:
- job: Windows

  variables: 
    BuildConfiguration: Release
    
  steps:
  - task: BatchScript@1
    inputs:
      filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
      arguments: -no_logo
      modifyEnvironment: true
    displayName: Setup Environment Variables
    
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 4.7.0
    inputs:
      versionSpec: 4.7.0
  
  - task: DotNetCoreCLI@2  
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv
    displayName: Install NBGV tool
  
  - script: nbgv cloud
    displayName: Set Version
  
  - powershell: .\build\Install-WindowsSdkISO.ps1 17763
    displayName: Insider SDK
  
  - powershell: .\build\build.ps1 -target=Package
    displayName: Build 
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: .\Microsoft.Toolkit.Uwp.SampleApp.Wasm\bin\Release\netstandard2.0\dist
      artifactType: container
      artifactName: Wasm
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: .\bin\nupkg
      artifactType: container
      artifactName: WCT-Packages
    condition: always()

- job: linux
  pool:
    name: Default
    demands:
    - agent.os -equals Linux 

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true
  
  - bash: |
      sudo apt-get update
      sudo apt-get install libc6
      cd $(build.sourcesdirectory)
      wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
      unzip -o ninja-linux.zip -d ninja-linux

    displayName: 'Install Ninja'

  - bash: |
      cd $(build.sourcesdirectory)
      git clone https://github.com/juj/emsdk.git
      cd emsdk
      ./emsdk install sdk-1.38.28-64bit
      ./emsdk activate sdk-1.38.28-64bit

    displayName: 'Install Emscripten'

  - bash: |
      export PATH=$PATH:$(build.sourcesdirectory)/ninja-linux
      source $(build.sourcesdirectory)/emsdk/emsdk_env.sh
      msbuild /r /p:Configuration=Release $(build.sourcesdirectory)/Microsoft.Toolkit.Uwp.SampleApp.Wasm/Microsoft.Toolkit.Uwp.SampleApp.Wasm.csproj /p:TargetFrameworksOverride=netstandard2.0 /bl:$(build.artifactstagingdirectory)\build.binlog

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/Microsoft.Toolkit.Uwp.SampleApp.Wasm/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/wct-wasm/$(RuntimeMode)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false


  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: wct-aot-drop
      ArtifactType: Container